name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Requirements
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Install Requirements
      run: yarn run deploy
