name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Requirements
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Building project
        run: yarn run build
        shell: bash

      - name: Git configuration
        run: git config user.name github-actions && git config user.email github-actions@github.com && git --work-tree build add --all
        shell: bash

      - name: Git commit
        run: git commit -m "Automatic Deploy action run by github-actions"
        shell: bash

      - name: Git push
        run: git push origin HEAD:gh-pages --force
        shell: bash
